### ISSUE TITLE
Sanity error: ClientError: The mutation(s) failed: mutation failed... Insufficient permissions; permission "create" required

### ISSUE THREAD

**Issue by jamesanderegg** [lucasvocos/gatsby-sanity-shopify#5]
Hello! Everything is connected and everything deploys fine but when I use Shopify to either send a test request or update a product, the Shopify function catches an error.  I'm pretty sure Netlify has all the permissions and variables it needs.  I'm sure this is something simple but I'm having a hard time debugging this.  

`Sanity error 4: ClientError: The mutation(s) failed: mutation failed on document "788032119674292900": Insufficient permissions; permission "create" required
    at onResponse (/var/task/src/node_modules/@sanity/client/lib/http/request.js:27:13)
    at /var/task/src/node_modules/get-it/lib-node/util/middlewareReducer.js:10:22
    at Array.reduce (<anonymous>)
    at applyMiddleware (/var/task/src/node_modules/get-it/lib-node/util/middlewareReducer.js:9:29)
    at onResponse (/var/task/src/node_modules/get-it/lib-node/index.js:81:22)
    at /var/task/src/node_modules/get-it/lib-node/index.js:48:55
    at callback (/var/task/src/node_modules/get-it/lib-node/request/node-request.js:57:46)
    at /var/task/src/node_modules/get-it/lib-node/request/node-request.js:141:14
    at DestroyableTransform.<anonymous> (/var/task/src/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:420:28) {
  response: {
    body: { error: [Object] },
    url: '***************************************',
    method: 'POST',
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'content-length': '349',
      'x-sanity-shard': '*********************',
      'x-served-by': '*************',
      date: '********************',
      vary: 'Origin',
      xkey: 'project-************, project-******************',
      via: '1.1 google',
      'alt-svc': 'clear',
      connection: 'close'
    },
    statusCode: 403,
    statusMessage: 'Forbidden'
  }`

**Comment by jamesanderegg** [comment]
Whoops I figured it out.

**Comment by mrideout1985** [comment]
what was the solution?

**Comment by jamesanderegg** [comment]
I can't remember if I needed WRITE settings but either way, my API key was setup without READ/WRITE settings so I made a new key with the proper permissions.

**Comment by jamesanderegg** [comment]
My API key was setup without "READ" settings so I made a new key with the proper permissions.

**Comment by jaynerdominguez** [comment]
@jamesanderegg Did you add a new token on Sanity? Just wanted to know what API key you re-made in. Please let me know. Thank you

**Comment by jamesanderegg** [comment]
> @jamesanderegg Did you add a new token on Sanity? Just wanted to know what API key you re-made in. Please let me know. Thank you

@jaynerdominguez I had accidentally set up a token using Deploy Studio rights instead of read and write settings so I deleted my old token and made a new one.

**Comment by edenma5** [comment]
Unfortunately, it doesn't work for me despite the permissions.
I have a form on the website and when I try to send it, it gives me an error.

**Comment by parshwa26122002** [comment]
1) If you are using Next.js then your token's env variable must have "NEXT_PUBLIC_" as prefix.
eg: "NEXT_PUBLIC_SANITY_USER_ADDER_TOKEN"
Then use it anywhere as: process.env.NEXT_PUBLIC_SANITY_USER_ADDER_TOKEN

2) Make sure your env file is in root directory.

3) create token with "Editor" permission in your Manage project - API Section

4) Add that token to your client.
