### ISSUE TITLE
Cannot get description field from Shopify in Sanity or Gatsby

### ISSUE THREAD

**Issue by petercr** [lucasvocos/gatsby-sanity-shopify#6]
**Describe the bug**
With the project up and running I noticed that while I was getting most of the product data back in the GraphQL queries from Sanity. However, the description text box on the Sanity Studio doesn't show anything. 
The text box is just blank and it says "Click to Active"

So, I decided to open up the GraphiQL playground on the local Gatsby build. 
I ran both the `allSanityProduct` and the `sanityProduct` queries to see if I could find it buried somewhere 🤷‍♂️ 
When I query `content` or `description` fields they all get returned as `null` 😢 

**To Reproduce**
1. Start up working Sanity Studio in `/studio/` with `sanity start`
2. Open up local Studio at `http://localhost:3333`
3. Navigate to the Products Section 
4. Notice that "Product Description" is blank.
5. Run a bunch of queries through Gatsby's GraphiQL explorer

**Expected behavior**
That the product description data would have been passed along with all the other data from Shopify to Sanity.
In `studio/schemas/product.js` the schema references `productDescription` field, but it seems to be empty.

**Screenshots**
Here's a screenshot of the local Sanity Studio with the Procut Description text box blank. 
There is data on the Shopify store that should show up. 

![sanity-studio](https://user-images.githubusercontent.com/26460352/105435175-dc56f400-5c2a-11eb-9e84-4b9db20a1d16.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser [Chrome, FireFox, Edge]
 - Version [87.0.4280.141, 84.0.2, 87.0.664.75]

**Additional context**
Here are the GraphQL queries that I tried running to get the description for any product 

```graphql
query MyQuery {
  allSanityProduct {
    edges {
      node {
        internal {
          content
          contentDigest
          description
        }
        productDescription {
          children {
            text
          }
        }
      }
    }
    nodes {
      internal {
        content
        contentDigest
        description
      }
      title
      productDescription {
        children {
          text
        }
      }
      variants {
        internal {
          content
          contentDigest
        }
        productDescription {
          children {
            text
          }
        }
      }
    }
  }
}

```

And here's the JSON data I got back:

```json
{
  "data": {
    "allSanityProduct": {
      "edges": [
        {
          "node": {
            "internal": {
              "content": null,
              "contentDigest": "71ebec409bd850721f517459be595901",
              "description": null
            },
            "productDescription": null
          }
        },
        {
          "node": {
            "internal": {
              "content": null,
              "contentDigest": "b2ba54f33b95a0172fa3bc8f19f2cc76",
              "description": null
            },
            "productDescription": null
          }
        }
      ],
      "nodes": [
        {
          "internal": {
            "content": null,
            "contentDigest": "71ebec409bd850721f517459be595901",
            "description": null
          },
          "title": "Pants",
          "productDescription": null,
          "variants": []
        },
        {
          "internal": {
            "content": null,
            "contentDigest": "b2ba54f33b95a0172fa3bc8f19f2cc76",
            "description": null
          },
          "title": "Example T-Shirt",
          "productDescription": null,
          "variants": [
            {
              "internal": {
                "content": null,
                "contentDigest": "86ffc29b8f258159c2ed008af670ac2c"
              },
              "productDescription": null
            },
            {
              "internal": {
                "content": null,
                "contentDigest": "86322b6f8e735714bde503590091a348"
              },
              "productDescription": null
            }
          ]
        }
      ],
      "group": [
        {
          "nodes": [
            {
              "internal": {
                "content": null,
                "description": null
              }
            }
          ]
        },
        {
          "nodes": [
            {
              "internal": {
                "content": null,
                "description": null
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {}
}
```

**Comment by petercr** [comment]
Whoops I think I figured out what it is not working 🤔 
So when you look at the `shopify.js` function, when `product` is defined on line 49, it _**does not**_ have a field for description. 😂  

The answer to my question it seems, is that the function is not pulling in that data 🤦 
Once I get it working I will send over a PR with the updated function 👍

**Comment by lucasvocos** [comment]
@petercr glad you were able to figure it out! I purposely left it really vague & lightweight so that the bulk of your content could be managed in Sanity.
